name: famedlysdk
description: Matrix Dart SDK
version: 0.1.0
author: Famedly GmbH <info@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  mime: ^1.0.0
  canonical_json: ^1.1.0
  markdown: ^4.0.0
  html_unescape: ^2.0.0
  moor: ^4.4.1
  random_string: ^2.3.1
  crypto: ^3.0.1
  base58check: ^2.0.0
  olm: ^2.0.0
  isolate: ^2.1.1
  matrix_api_lite: ^0.4.0

dev_dependencies:
  test: ^1.17.10
  coverage: ^1.0.3
  moor_generator: ^4.4.1
  build_runner: ^2.0.6
  pedantic: ^1.11.1
  dapackages: ^1.6.0
  #flutter_test: {sdk: flutter}
